parametros = {'gamas': ('Baja', 'Media', 'Alta'),
 'tipoPersonas': ('Natural', 'Juridica'),
 'tiposTraccion': ('', 'Delantera', 'Trasera', '4x4'),
 'tiposMantenimiento': ('Preventivo', 'Correctivo'),
 'misionInicio': u'En este texto se puede modificar la misi\xf3n que aparece en el inicio de la plataforma. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repudiandae, perferendis iure aspernatur eligendi in minima pariatur natus labore modi nesciunt molestias nisi minus assumenda nulla a sint distinctio commodi dolor.', 'tipoDocumentos': ('C.C.', 'Pasaporte', 'NIT', 'Otro'),
 'quienesSomosInicio': u'En este texto se puede modificar el quienes somos que aparece en la inicio de la plataforma. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi, quas, voluptas, aperiam nostrum error quo porro veritatis accusantium recusandae voluptatum ipsum saepe magni natus repellendus quaerat magnam iste dicta neque.', 'numElementosPorPagina': u'10', 'estadosVehiculo': ('Disponible', 'Reservado', 'Rentado', 'En Mantenimiento'),
 'cajasDeCambios': ('Automatica', 'Manual', 'Triptonica'),
 'generos': ('Prefiero no decir', 'Masculino', 'Femenino'),
 'tipoDeDirecciones': ('', 'Mecanica', 'Hidraulica', 'Electronica'),
 'visionInicio': u'En este texto se puede modificar la visi\xf3n que aparece en la inicio de la plataforma. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente, consectetur aperiam recusandae magnam veniam voluptas neque animi rerum quo sed! Accusantium nemo quasi error consectetur vero deserunt molestiae autem incidunt.', 'tiposDeFrenos': ('', 'Disco', 'Tambor', 'ABS'),
 'estadosPago': ('No', 'Si')}