parametros = {'gamas': ('Baja', 'Media', 'Alta'),
 'tipoPersonas': ('Natural', 'Juridica'),
 'tiposTraccion': ('', 'Delantera', 'Trasera', '4x4'),
 'tiposMantenimiento': ('Preventivo', 'Correctivo'),
 'misionInicio': u'La mision es la que la profe diga.', 'tipoDocumentos': ('C.C.', 'Pasaporte', 'NIT', 'Otro'),
 'quienesSomosInicio': u'Gente emprendedora', 'numElementosPorPagina': u'10', 'estadosVehiculo': ('Disponible', 'Reservado', 'Rentado', 'En Mantenimiento'),
 'cajasDeCambios': ('Automatica', 'Manual', 'Triptonica'),
 'tipoDeDirecciones': ('', 'Mecanica', 'Hidraulica', 'Electronica'),
 'generos': ('Prefiero no decir', 'Masculino', 'Femenino'),
 'visionInicio': u'Visi\xf3n al futuro', 'tiposDeFrenos': ('', 'Disco', 'Tambor', 'ABS'),
 'estadosPago': ('No', 'Si')}