parametros = {'gamas': ('Baja', 'Media', 'Alta'),
 'tipoPersonas': ('Natural', 'Empresa'),
 'servicios': {'Gasolina': 2,'Entrega': 5,'Recogida': 6, 'Lavada': 3, 'Alquiler': 1, 'Conductor': 4}, 'tiposTraccion': ('', 'Delantera', 'Trasera', '4x4'),
 'tiposMantenimiento': ('Preventivo', 'Correctivo'),
 'misionInicio': u'En este campo se ingresa la misi\xf3n de la empresa.', 'tipoDocumentos': ('C.C.', 'Pasaporte', 'NIT', 'Otro'),
 'tipoDeDirecciones': ('', 'Mecanica', 'Hidraulica', 'Electronica'),
 'lavada': {'Pequeno': 7000, 'Grande': 15000, 'Mediano': 10000}, 'nombreEmpresa': u'Your Car', 'generos': ('Prefiero no decir', 'Masculino', 'Femenino'),
 'estadosPago': ('No', 'Si'),
 'tiposDeFrenos': ('', 'Disco', 'Tambor', 'ABS', 'Tambor_Disco'),
 'metodosPago': ('Efectivo', 'Cheque', 'Tarjeta Credito', 'Tarjeta Debito', 'PayPal'), 'galonGasolina': u'10000', 'quienesSomosInicio': u'Datos de la empresa', 'numElementosPorPagina': u'10', 'estadosVehiculo': ('Disponible', 'Reservado', 'Rentado', 'En Mantenimiento'),
 'lugaresCostos': {'Otro': 15000, 'Aeropuerto': 10000, 'Empresa': 0}, 'cajasDeCambios': ('Automatica', 'Manual', 'Triptonica'),
 'IVA': u'16', 'visionInicio': u'En este campo se ingresa la vision de la empresa.', 'nitEmpresa': u'123456789'}